branches:
  only:
    - master

before_install:
  - env

before_script:
  - bundle exec rake

bundler_args: --without doc test

cache:
  - apt
  - bundler

language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
